export const FETCH_DATA_DOLLAR = 'FETCH_DATA_DOLLAR';
export const FETCH_DATA_CURRENT_SUCCESS = 'FETCH_DATA_CURRENT_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_HISTORY_SUCCESS = 'FETCH_DATA_HISTORY_SUCCESS';
export const UPDATE_DATES = 'UPDATE_DATES';
